ggplot(mtcars, aes(mpg, wt)) + geom_point(aes(colour = factor(cyl)))                                                                               ; # vs ...
ggplot(mtcars, aes(mpg, wt)) + geom_point(aes(colour = factor(cyl))) + scale_colour_manual(values = c(      'black',       'orange',       'cyan')); # vs ...
ggplot(mtcars, aes(mpg, wt)) + geom_point(aes(colour = factor(cyl))) + scale_colour_manual(values = c('6' = 'black', '8' = 'orange', '4' = 'cyan')); # vs ...

ggplot(mtcars, aes(mpg, wt, color = factor(cyl), fill = factor(cyl)) ) +  geom_point(shape = 21, alpha = 0.5, size = 2); # vs
# ? ggplot(mtcars, aes(mpg, wt, color = factor(cyl), fill = factor(cyl)) ) +  geom_point(shape = 21, alpha = 0.5, size = 2) + scale_color_manual( values = c('6' = 'black', '8' = 'orange', '4' = 'cyan'), aesthetics = c('color', 'fill') )

